# Generated by Django 5.2.1 on 2026-01-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterField(
            model_name='livesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
