# Generated by Django 4.2.21 on 2026-02-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_alter_livesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='canva_embed_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='livesession',
            name='external_view_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='livesession',
            name='live_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='livesession',
            name='pptx_file',
            field=models.FileField(blank=True, null=True, upload_to='live/pptx/'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='source_type',
            field=models.CharField(choices=[('slides', 'Slides'), ('canva', 'Canva'), ('url', 'External URL'), ('pptx', 'PPTX')], default='slides', max_length=16),
        ),
    ]
