# Generated by Django 4.2.21 on 2026-02-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_livesession_canva_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='pptx_preview_pdf',
            field=models.FileField(blank=True, null=True, upload_to='live/pptx_preview/'),
        ),
    ]
