# Generated by Django 4.2.21 on 2026-02-19 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live', '0004_livesession_pptx_preview_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='timer_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livesession',
            name='timer_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LiveParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('points', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('checkins_count', models.PositiveIntegerField(default=0)),
                ('current_slide_index', models.IntegerField(default=0)),
                ('last_checked_slide_index', models.IntegerField(default=-1)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', '-best_streak', 'joined_at', 'id'],
                'unique_together': {('live_session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='LiveSlideCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_index', models.PositiveIntegerField(default=0)),
                ('reaction_ms', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_checkins', to='live.livesession')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_checkins', to='live.liveparticipant')),
            ],
            options={
                'ordering': ['live_session_id', 'slide_index', 'created_at', 'id'],
                'indexes': [models.Index(fields=['live_session', 'slide_index'], name='live_livesl_live_se_fc895e_idx'), models.Index(fields=['participant', 'slide_index'], name='live_livesl_partici_6ea5db_idx')],
                'unique_together': {('participant', 'slide_index')},
            },
        ),
    ]
