# Generated by Django 4.2.21 on 2026-02-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_assignment_assignment_type_assignment_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resources',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
