# Generated by Django 4.2.21 on 2026-02-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_assessment_lesson_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
