# Generated by Django 4.2.21 on 2026-02-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_experiment_experimentparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('sorting', 'Sorting'), ('matching', 'Matching'), ('poll', 'Poll'), ('slides', 'Slides'), ('grouping', 'Grouping'), ('flashcards', 'Flashcards'), ('crossword', 'Crossword'), ('other', 'Other')], default='quiz', max_length=32),
        ),
    ]
