# Generated by Django 4.2.21 on 2025-11-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games1', '0003_gamesession_player_delete_gamequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('sorting', 'Порядок сортировки')], default='sorting', max_length=32)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
