# Generated by Django 5.2.1 on 2026-01-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games1', '0004_gametemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameTemplate',
        ),
    ]
