# Generated by Django 4.2.21 on 2026-02-16 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_submission_duration_seconds'),
        ('users', '0002_user_full_name_user_school_user_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('min_success_rate', models.FloatField(default=0.0)),
                ('max_success_rate', models.FloatField(default=1.0)),
                ('min_attempts', models.PositiveIntegerField(default=3)),
                ('action', models.CharField(choices=[('increase_difficulty', 'Increase Difficulty'), ('decrease_difficulty', 'Decrease Difficulty'), ('reinforce_topic', 'Reinforce Weak Topics')], default='reinforce_topic', max_length=30)),
                ('recommendation_template', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_success_rate', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('interest_focus', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_formats', models.JSONField(blank=True, default=list)),
                ('learning_goals', models.TextField(blank=True, default='')),
                ('average_score', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('total_points', models.IntegerField(default=0)),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('strong_topics', models.JSONField(blank=True, default=list)),
                ('progress_history', models.JSONField(blank=True, default=list)),
                ('last_recommendation', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LearningTrajectoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('required_score', models.FloatField(default=0.6)),
                ('mastery', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('in_progress', 'In Progress'), ('review', 'Needs Review'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('recommendation', models.CharField(blank=True, default='', max_length=255)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectory_nodes', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectory_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_id', 'order_index', 'id'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
