# Generated by Django 5.2.1 on 2025-06-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='slide',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slide',
            name='drawing_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slide_images/'),
        ),
    ]
