# Generated by Django 5.2.1 on 2025-06-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0002_remove_slide_updated_at_slide_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='answer',
        ),
        migrations.AddField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
    ]
