# Generated by Django 5.2.1 on 2025-06-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0003_remove_slide_answer_slide_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('drawing', 'Drawing')], max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='slide.slide')),
            ],
        ),
    ]
