# Generated by Django 5.2.1 on 2025-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0004_slideobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='content',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='drawing_data',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='slideobject',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='object_type',
            field=models.CharField(max_length=50),
        ),
    ]
