# Generated by Django 5.2.1 on 2025-09-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('slide', '0006_slidetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='lesson',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='lessons.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_objects', to='slide.slide'),
        ),
    ]
