# Generated by Django 4.2.21 on 2025-09-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0007_slide_lesson_alter_slideobject_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideobject',
            name='position',
            field=models.JSONField(default=dict, help_text='{x,y,width,height}'),
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='data',
            field=models.JSONField(help_text='Typed payload: e.g., text/fontSize/color/url/path/shapeType, etc.'),
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='object_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('drawing', 'Drawing'), ('shape', 'Shape'), ('attachment', 'Attachment'), ('checkbox', 'Checkbox')], max_length=50),
        ),
    ]
