# Generated by Django 4.2.21 on 2025-09-12 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import slide.models


def backfill_slide_order(apps, schema_editor):
    Slide = apps.get_model('slide', 'Slide')
    # Бар слайдтарды lesson_id, id арқылы реттеп,
    # әр сабақ ішінде ретті order беріп шығамыз
    current_lesson = None
    counter = 0
    for s in Slide.objects.order_by('lesson_id', 'id'):
        if s.lesson_id != current_lesson:
            current_lesson = s.lesson_id
            counter = 0
        counter += 1
        # тек order жоқ болса немесе 0 болса қоямыз
        if getattr(s, 'order', None) in (None, 0):
            s.order = counter
            s.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slide', '0008_slideobject_position_alter_slideobject_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['lesson_id', 'order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='slideobject',
            options={'ordering': ['slide_id', 'z_index', 'id']},
        ),
        migrations.AlterModelOptions(
            name='slidetemplate',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AddField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        # Populate order per lesson before applying unique_together
        migrations.RunPython(backfill_slide_order, migrations.RunPython.noop),
        migrations.AddField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slideobject',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slideobject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slideobject',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slideobject',
            name='rotation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='slideobject',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slideobject',
            name='z_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='data',
            field=models.JSONField(default=slide.models._empty_dict, help_text='Typed payload'),
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='object_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('drawing', 'Drawing'), ('shape', 'Shape'), ('attachment', 'Attachment'), ('checkbox', 'Checkbox')], max_length=32),
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='position',
            field=models.JSONField(default=slide.models._empty_dict),
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together={('lesson', 'order')},
        ),
        migrations.AddIndex(
            model_name='slideobject',
            index=models.Index(fields=['slide', 'object_type'], name='slide_slide_slide_i_d3f1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='slideobject',
            index=models.Index(fields=['slide', 'z_index'], name='slide_slide_slide_i_02566a_idx'),
        ),
    ]
