# Generated by Django 4.2.21 on 2025-09-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0009_alter_slide_options_alter_slideobject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
