# Generated by Django 5.2.1 on 2025-09-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0010_alter_slide_updated_at_alter_slideobject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidetemplate',
            name='template_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('matching', 'Matching'), ('flashcards', 'Flashcards'), ('poll', 'Poll/Survey'), ('crossword', 'Crossword')], default='quiz', max_length=32),
        ),
        migrations.AlterField(
            model_name='slidetemplate',
            name='data',
            field=models.JSONField(help_text='Template config (e.g., quiz Q&A, matching pairs, etc.)'),
        ),
    ]
