# Generated by Django 5.2.1 on 2026-01-24 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_description_alter_lesson_share_code_and_more'),
        ('slide', '0012_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='slidetemplate',
            name='data',
            field=models.JSONField(help_text='Template config (quiz/matching/etc.)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_submissions', related_query_name='slide_submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='slide',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='uniq_slide_order_per_lesson'),
        ),
    ]
