# Generated by Django 4.2.21 on 2026-02-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0013_alter_slide_unique_together_alter_slidetemplate_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slidetemplate',
            name='template_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('matching', 'Matching'), ('flashcards', 'Flashcards'), ('poll', 'Poll/Survey'), ('crossword', 'Crossword'), ('sorting', 'Sorting'), ('grouping', 'Grouping')], default='quiz', max_length=32),
        ),
    ]
