# Generated by Django 4.2.21 on 2026-01-28 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortingtemplate',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='sortingtemplate',
            name='items',
        ),
        migrations.AddField(
            model_name='sortingtemplate',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sortingtemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorting_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sortingtemplate',
            name='template_type',
            field=models.CharField(default='sorting', max_length=32),
        ),
        migrations.AlterField(
            model_name='sortingtemplate',
            name='title',
            field=models.CharField(default='Sorting template', max_length=255),
        ),
    ]
